version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      LISTEN_ADDR: :8080
      CONN_STR: postgres://postgres:postgres@db:5432/bankapi
      SECRET_KEY: DAYSOFMADNESS
    command: ["./bin/bank-api"]

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bankapi
    ports:
      - "5433:5432"